export enum CountryCode {
	AD = 'AD',
	AE = 'AE',
	AF = 'AF',
	AG = 'AG',
	AI = 'AI',
	AL = 'AL',
	AM = 'AM',
	AO = 'AO',
	AQ = 'AQ',
	AR = 'AR',
	AS = 'AS',
	AT = 'AT',
	AU = 'AU',
	AW = 'AW',
	AX = 'AX',
	AZ = 'AZ',
	BA = 'BA',
	BB = 'BB',
	BD = 'BD',
	BE = 'BE',
	BF = 'BF',
	BG = 'BG',
	BH = 'BH',
	BI = 'BI',
	BJ = 'BJ',
	BL = 'BL',
	BM = 'BM',
	BN = 'BN',
	BO = 'BO',
	BQ = 'BQ',
	BR = 'BR',
	BS = 'BS',
	BT = 'BT',
	BV = 'BV',
	BW = 'BW',
	BY = 'BY',
	BZ = 'BZ',
	CA = 'CA',
	CC = 'CC',
	CD = 'CD',
	CF = 'CF',
	CG = 'CG',
	CH = 'CH',
	CI = 'CI',
	CK = 'CK',
	CL = 'CL',
	CM = 'CM',
	CN = 'CN',
	CO = 'CO',
	CR = 'CR',
	CU = 'CU',
	CV = 'CV',
	CW = 'CW',
	CX = 'CX',
	CY = 'CY',
	CZ = 'CZ',
	DE = 'DE',
	DJ = 'DJ',
	DK = 'DK',
	DM = 'DM',
	DO = 'DO',
	DZ = 'DZ',
	EC = 'EC',
	EE = 'EE',
	EG = 'EG',
	EH = 'EH',
	ER = 'ER',
	ES = 'ES',
	ET = 'ET',
	FI = 'FI',
	FJ = 'FJ',
	FK = 'FK',
	FM = 'FM',
	FO = 'FO',
	FR = 'FR',
	GA = 'GA',
	GB = 'GB',
	GD = 'GD',
	GE = 'GE',
	GF = 'GF',
	GG = 'GG',
	GH = 'GH',
	GI = 'GI',
	GL = 'GL',
	GM = 'GM',
	GN = 'GN',
	GP = 'GP',
	GQ = 'GQ',
	GR = 'GR',
	GS = 'GS',
	GT = 'GT',
	GU = 'GU',
	GW = 'GW',
	GY = 'GY',
	HK = 'HK',
	HM = 'HM',
	HN = 'HN',
	HR = 'HR',
	HT = 'HT',
	HU = 'HU',
	ID = 'ID',
	IE = 'IE',
	IL = 'IL',
	IM = 'IM',
	IN = 'IN',
	IO = 'IO',
	IQ = 'IQ',
	IR = 'IR',
	IS = 'IS',
	IT = 'IT',
	JE = 'JE',
	JM = 'JM',
	JO = 'JO',
	JP = 'JP',
	KE = 'KE',
	KG = 'KG',
	KH = 'KH',
	KI = 'KI',
	KM = 'KM',
	KN = 'KN',
	KP = 'KP',
	KR = 'KR',
	KW = 'KW',
	KY = 'KY',
	KZ = 'KZ',
	LA = 'LA',
	LB = 'LB',
	LC = 'LC',
	LI = 'LI',
	LK = 'LK',
	LR = 'LR',
	LS = 'LS',
	LT = 'LT',
	LU = 'LU',
	LV = 'LV',
	LY = 'LY',
	MA = 'MA',
	MC = 'MC',
	MD = 'MD',
	ME = 'ME',
	MF = 'MF',
	MG = 'MG',
	MH = 'MH',
	MK = 'MK',
	ML = 'ML',
	MM = 'MM',
	MN = 'MN',
	MO = 'MO',
	MP = 'MP',
	MQ = 'MQ',
	MR = 'MR',
	MS = 'MS',
	MT = 'MT',
	MU = 'MU',
	MV = 'MV',
	MW = 'MW',
	MX = 'MX',
	MY = 'MY',
	MZ = 'MZ',
	NA = 'NA',
	NC = 'NC',
	NE = 'NE',
	NF = 'NF',
	NG = 'NG',
	NI = 'NI',
	NL = 'NL',
	NO = 'NO',
	NP = 'NP',
	NR = 'NR',
	NU = 'NU',
	NZ = 'NZ',
	OM = 'OM',
	PA = 'PA',
	PE = 'PE',
	PF = 'PF',
	PG = 'PG',
	PH = 'PH',
	PK = 'PK',
	PL = 'PL',
	PM = 'PM',
	PN = 'PN',
	PR = 'PR',
	PS = 'PS',
	PT = 'PT',
	PW = 'PW',
	PY = 'PY',
	QA = 'QA',
	RE = 'RE',
	RO = 'RO',
	RS = 'RS',
	RU = 'RU',
	RW = 'RW',
	SA = 'SA',
	SB = 'SB',
	SC = 'SC',
	SD = 'SD',
	SE = 'SE',
	SG = 'SG',
	SH = 'SH',
	SI = 'SI',
	SJ = 'SJ',
	SK = 'SK',
	SL = 'SL',
	SM = 'SM',
	SN = 'SN',
	SO = 'SO',
	SR = 'SR',
	SS = 'SS',
	ST = 'ST',
	SV = 'SV',
	SX = 'SX',
	SY = 'SY',
	SZ = 'SZ',
	TC = 'TC',
	TD = 'TD',
	TF = 'TF',
	TG = 'TG',
	TH = 'TH',
	TJ = 'TJ',
	TK = 'TK',
	TL = 'TL',
	TM = 'TM',
	TN = 'TN',
	TO = 'TO',
	TR = 'TR',
	TT = 'TT',
	TV = 'TV',
	TW = 'TW',
	TZ = 'TZ',
	UA = 'UA',
	UG = 'UG',
	UM = 'UM',
	US = 'US',
	UY = 'UY',
	UZ = 'UZ',
	VA = 'VA',
	VC = 'VC',
	VE = 'VE',
	VG = 'VG',
	VI = 'VI',
	VN = 'VN',
	VU = 'VU',
	WF = 'WF',
	WS = 'WS',
	YE = 'YE',
	YT = 'YT',
	ZA = 'ZA',
	ZM = 'ZM',
	ZW = 'ZW',
}

enum Region {
	Europe = 'Europe',
	Africa = 'Africa',
	Asia = 'Asia',
	MiddleEast = 'Middle East',
	NorthAmerica = 'North America',
	SouthAmerica = 'South America',
	CentralAmerica = 'Central America',
	Oceania = 'Oceania',
	Antarctica = 'Antarctica',
}

export type CountryList = Record<string, { name: string; hasFlag: boolean; region?: Region }>;

export const CountryDetails: CountryList = {
	AD: { name: 'Andorra', hasFlag: false, region: Region.Europe },
	AE: { name: 'United Arab Emirates', hasFlag: false, region: Region.MiddleEast },
	AF: { name: 'Afghanistan', hasFlag: true, region: Region.Asia },
	AG: { name: 'Antigua and Barbuda', hasFlag: false, region: Region.NorthAmerica },
	AI: { name: 'Anguilla', hasFlag: false, region: Region.NorthAmerica },
	AL: { name: 'Albania', hasFlag: true, region: Region.Europe },
	AM: { name: 'Armenia', hasFlag: true, region: Region.Europe },
	AO: { name: 'Angola', hasFlag: false, region: Region.Africa },
	AQ: { name: 'Antarctica', hasFlag: false, region: Region.Antarctica },
	AR: { name: 'Argentina', hasFlag: false, region: Region.SouthAmerica },
	AS: { name: 'American Samoa', hasFlag: false, region: Region.Oceania },
	AT: { name: 'Austria', hasFlag: false, region: Region.Europe },
	AU: { name: 'Australia', hasFlag: false, region: Region.Oceania },
	AW: { name: 'Aruba', hasFlag: false, region: Region.NorthAmerica },
	AX: { name: 'Åland Islands', hasFlag: false, region: Region.Europe },
	AZ: { name: 'Azerbaijan', hasFlag: true, region: Region.Europe },
	BA: { name: 'Bosnia and Herzegovina', hasFlag: true, region: Region.Europe },
	BB: { name: 'Barbados', hasFlag: false, region: Region.NorthAmerica },
	BD: { name: 'Bangladesh', hasFlag: true, region: Region.Asia },
	BE: { name: 'Belgium', hasFlag: false, region: Region.Europe },
	BF: { name: 'Burkina Faso', hasFlag: false, region: Region.Africa },
	BG: { name: 'Bulgaria', hasFlag: true, region: Region.Europe },
	BH: { name: 'Bahrain', hasFlag: false, region: Region.MiddleEast },
	BI: { name: 'Burundi', hasFlag: false, region: Region.Africa },
	BJ: { name: 'Benin', hasFlag: false, region: Region.Africa },
	BL: { name: 'Saint Barthélemy', hasFlag: false, region: Region.NorthAmerica },
	BM: { name: 'Bermuda', hasFlag: false, region: Region.NorthAmerica },
	BN: { name: 'Brunei Darussalam', hasFlag: false, region: Region.Asia },
	BO: { name: 'Bolivia, Plurinational State of', hasFlag: true, region: Region.SouthAmerica },
	BQ: { name: 'Bonaire, Sint Eustatius and Saba', hasFlag: false, region: Region.NorthAmerica },
	BR: { name: 'Brazil', hasFlag: false, region: Region.SouthAmerica },
	BS: { name: 'Bahamas', hasFlag: false, region: Region.NorthAmerica },
	BT: { name: 'Bhutan', hasFlag: false, region: Region.Asia },
	BV: { name: 'Bouvet Island', hasFlag: false, region: Region.Antarctica },
	BW: { name: 'Botswana', hasFlag: false, region: Region.Africa },
	BY: { name: 'Belarus', hasFlag: true, region: Region.Europe },
	BZ: { name: 'Belize', hasFlag: false, region: Region.CentralAmerica },
	CA: { name: 'Canada', hasFlag: false, region: Region.NorthAmerica },
	CC: { name: 'Cocos (Keeling) Islands', hasFlag: false, region: Region.Asia },
	CD: { name: 'Congo, Democratic Republic of the', hasFlag: true, region: Region.Africa },
	CF: { name: 'Central African Republic', hasFlag: false, region: Region.Africa },
	CG: { name: 'Congo', hasFlag: false, region: Region.Africa },
	CH: { name: 'Switzerland', hasFlag: false, region: Region.Europe },
	CI: { name: "Côte d'Ivoire", hasFlag: false, region: Region.Africa },
	CK: { name: 'Cook Islands', hasFlag: false, region: Region.Oceania },
	CL: { name: 'Chile', hasFlag: false, region: Region.SouthAmerica },
	CM: { name: 'Cameroon', hasFlag: false, region: Region.Africa },
	CN: { name: 'China', hasFlag: true, region: Region.Asia },
	CO: { name: 'Colombia', hasFlag: false, region: Region.SouthAmerica },
	CR: { name: 'Costa Rica', hasFlag: false, region: Region.CentralAmerica },
	CU: { name: 'Cuba', hasFlag: false, region: Region.NorthAmerica },
	CV: { name: 'Cabo Verde', hasFlag: false, region: Region.Africa },
	CW: { name: 'Curaçao', hasFlag: false, region: Region.NorthAmerica },
	CX: { name: 'Christmas Island', hasFlag: false, region: Region.Asia },
	CY: { name: 'Cyprus', hasFlag: false, region: Region.Europe },
	CZ: { name: 'Czechia', hasFlag: true, region: Region.Europe },
	DE: { name: 'Germany', hasFlag: true, region: Region.Europe },
	DJ: { name: 'Djibouti', hasFlag: false, region: Region.Africa },
	DK: { name: 'Denmark', hasFlag: true, region: Region.Europe },
	DM: { name: 'Dominica', hasFlag: false, region: Region.NorthAmerica },
	DO: { name: 'Dominican Republic', hasFlag: false, region: Region.NorthAmerica },
	DZ: { name: 'Algeria', hasFlag: false, region: Region.Africa },
	EC: { name: 'Ecuador', hasFlag: false, region: Region.SouthAmerica },
	EE: { name: 'Estonia', hasFlag: true, region: Region.Europe },
	EG: { name: 'Egypt', hasFlag: false, region: Region.Africa },
	EH: { name: 'Western Sahara', hasFlag: false, region: Region.Africa },
	ER: { name: 'Eritrea', hasFlag: true, region: Region.Africa },
	ES: { name: 'Spain', hasFlag: true, region: Region.Europe },
	ET: { name: 'Ethiopia', hasFlag: true, region: Region.Africa },
	FI: { name: 'Finland', hasFlag: true, region: Region.Europe },
	FJ: { name: 'Fiji', hasFlag: false, region: Region.Oceania },
	FK: { name: 'Falkland Islands (Malvinas)', hasFlag: false, region: Region.SouthAmerica },
	FM: { name: 'Micronesia, Federated States of', hasFlag: false, region: Region.Oceania },
	FO: { name: 'Faroe Islands', hasFlag: false, region: Region.Europe },
	FR: { name: 'France', hasFlag: true, region: Region.Europe },
	GA: { name: 'Gabon', hasFlag: false, region: Region.Africa },
	GB: { name: 'United Kingdom of Great Britain and Northern Ireland', hasFlag: true, region: Region.Europe },
	GD: { name: 'Grenada', hasFlag: false, region: Region.NorthAmerica },
	GE: { name: 'Georgia', hasFlag: true, region: Region.Europe },
	GF: { name: 'French Guiana', hasFlag: false, region: Region.SouthAmerica },
	GG: { name: 'Guernsey', hasFlag: false, region: Region.Europe },
	GH: { name: 'Ghana', hasFlag: true, region: Region.Africa },
	GI: { name: 'Gibraltar', hasFlag: false, region: Region.Europe },
	GL: { name: 'Greenland', hasFlag: false, region: Region.NorthAmerica },
	GM: { name: 'Gambia', hasFlag: false, region: Region.Africa },
	GN: { name: 'Guinea', hasFlag: false, region: Region.Africa },
	GP: { name: 'Guadeloupe', hasFlag: false, region: Region.NorthAmerica },
	GQ: { name: 'Equatorial Guinea', hasFlag: false, region: Region.Africa },
	GR: { name: 'Greece', hasFlag: true, region: Region.Europe },
	GS: { name: 'South Georgia and the South Sandwich Islands', hasFlag: false, region: Region.Antarctica },
	GT: { name: 'Guatemala', hasFlag: false, region: Region.CentralAmerica },
	GU: { name: 'Guam', hasFlag: false, region: Region.Oceania },
	GW: { name: 'Guinea-Bissau', hasFlag: false, region: Region.Africa },
	GY: { name: 'Guyana', hasFlag: false, region: Region.SouthAmerica },
	HK: { name: 'Hong Kong', hasFlag: false, region: Region.Asia },
	HM: { name: 'Heard Island and McDonald Islands', hasFlag: false, region: Region.Antarctica },
	HN: { name: 'Honduras', hasFlag: false, region: Region.CentralAmerica },
	HR: { name: 'Croatia', hasFlag: true, region: Region.Europe },
	HT: { name: 'Haiti', hasFlag: true, region: Region.NorthAmerica },
	HU: { name: 'Hungary', hasFlag: true, region: Region.Europe },
	ID: { name: 'Indonesia', hasFlag: true, region: Region.Asia },
	IE: { name: 'Ireland', hasFlag: true, region: Region.Europe },
	IL: { name: 'Israel', hasFlag: true, region: Region.MiddleEast },
	IM: { name: 'Isle of Man', hasFlag: false, region: Region.Europe },
	IN: { name: 'India', hasFlag: true, region: Region.Asia },
	IO: { name: 'British Indian Ocean Territory', hasFlag: false, region: Region.Asia },
	IQ: { name: 'Iraq', hasFlag: true, region: Region.MiddleEast },
	IR: { name: 'Iran, Islamic Republic of', hasFlag: true, region: Region.MiddleEast },
	IS: { name: 'Iceland', hasFlag: true, region: Region.Europe },
	IT: { name: 'Italy', hasFlag: true, region: Region.Europe },
	JE: { name: 'Jersey', hasFlag: false, region: Region.Europe },
	JM: { name: 'Jamaica', hasFlag: false, region: Region.NorthAmerica },
	JO: { name: 'Jordan', hasFlag: false, region: Region.MiddleEast },
	JP: { name: 'Japan', hasFlag: true, region: Region.Asia },
	KE: { name: 'Kenya', hasFlag: false, region: Region.Africa },
	KG: { name: 'Kyrgyzstan', hasFlag: true, region: Region.Asia },
	KH: { name: 'Cambodia', hasFlag: true, region: Region.Asia },
	KI: { name: 'Kiribati', hasFlag: false, region: Region.Oceania },
	KM: { name: 'Comoros', hasFlag: false, region: Region.Africa },
	KN: { name: 'Saint Kitts and Nevis', hasFlag: false, region: Region.NorthAmerica },
	KP: { name: "Korea, Democratic People's Republic of", hasFlag: false, region: Region.Asia },
	KR: { name: 'Korea, Republic of', hasFlag: true, region: Region.Asia },
	KW: { name: 'Kuwait', hasFlag: false, region: Region.MiddleEast },
	KY: { name: 'Cayman Islands', hasFlag: false, region: Region.NorthAmerica },
	KZ: { name: 'Kazakhstan', hasFlag: true, region: Region.Asia },
	LA: { name: "Lao People's Democratic Republic", hasFlag: true, region: Region.Asia },
	LB: { name: 'Lebanon', hasFlag: false, region: Region.MiddleEast },
	LC: { name: 'Saint Lucia', hasFlag: false, region: Region.NorthAmerica },
	LI: { name: 'Liechtenstein', hasFlag: false, region: Region.Europe },
	LK: { name: 'Sri Lanka', hasFlag: true, region: Region.Asia },
	LR: { name: 'Liberia', hasFlag: false, region: Region.Africa },
	LS: { name: 'Lesotho', hasFlag: false, region: Region.Africa },
	LT: { name: 'Lithuania', hasFlag: true, region: Region.Europe },
	LU: { name: 'Luxembourg', hasFlag: true, region: Region.Europe },
	LV: { name: 'Latvia', hasFlag: true, region: Region.Europe },
	LY: { name: 'Libya', hasFlag: false, region: Region.Africa },
	MA: { name: 'Morocco', hasFlag: false, region: Region.Africa },
	MC: { name: 'Monaco', hasFlag: false, region: Region.Europe },
	MD: { name: 'Moldova, Republic of', hasFlag: false, region: Region.Europe },
	ME: { name: 'Montenegro', hasFlag: false, region: Region.Europe },
	MF: { name: 'Saint Martin (French part)', hasFlag: false, region: Region.NorthAmerica },
	MG: { name: 'Madagascar', hasFlag: true, region: Region.Africa },
	MH: { name: 'Marshall Islands', hasFlag: false, region: Region.Oceania },
	MK: { name: 'North Macedonia', hasFlag: true, region: Region.Europe },
	ML: { name: 'Mali', hasFlag: true, region: Region.Africa },
	MM: { name: 'Myanmar', hasFlag: true, region: Region.Asia },
	MN: { name: 'Mongolia', hasFlag: true, region: Region.Asia },
	MO: { name: 'Macao', hasFlag: false, region: Region.Asia },
	MP: { name: 'Northern Mariana Islands', hasFlag: false, region: Region.Oceania },
	MQ: { name: 'Martinique', hasFlag: false, region: Region.NorthAmerica },
	MR: { name: 'Mauritania', hasFlag: false, region: Region.Africa },
	MS: { name: 'Montserrat', hasFlag: false, region: Region.NorthAmerica },
	MT: { name: 'Malta', hasFlag: true, region: Region.Europe },
	MU: { name: 'Mauritius', hasFlag: false, region: Region.Africa },
	MV: { name: 'Maldives', hasFlag: true, region: Region.Asia },
	MW: { name: 'Malawi', hasFlag: true, region: Region.Africa },
	MX: { name: 'Mexico', hasFlag: false, region: Region.NorthAmerica },
	MY: { name: 'Malaysia', hasFlag: true, region: Region.Asia },
	MZ: { name: 'Mozambique', hasFlag: false, region: Region.Africa },
	NA: { name: 'Namibia', hasFlag: false, region: Region.Africa },
	NC: { name: 'New Caledonia', hasFlag: false, region: Region.Oceania },
	NE: { name: 'Niger', hasFlag: false, region: Region.Africa },
	NF: { name: 'Norfolk Island', hasFlag: false, region: Region.Oceania },
	NG: { name: 'Nigeria', hasFlag: true, region: Region.Africa },
	NI: { name: 'Nicaragua', hasFlag: false, region: Region.CentralAmerica },
	NL: { name: 'Netherlands, Kingdom of the', hasFlag: true, region: Region.Europe },
	NO: { name: 'Norway', hasFlag: true, region: Region.Europe },
	NP: { name: 'Nepal', hasFlag: true, region: Region.Asia },
	NR: { name: 'Nauru', hasFlag: false, region: Region.Oceania },
	NU: { name: 'Niue', hasFlag: false, region: Region.Oceania },
	NZ: { name: 'New Zealand', hasFlag: true, region: Region.Oceania },
	OM: { name: 'Oman', hasFlag: false, region: Region.MiddleEast },
	PA: { name: 'Panama', hasFlag: false, region: Region.CentralAmerica },
	PE: { name: 'Peru', hasFlag: true, region: Region.SouthAmerica },
	PF: { name: 'French Polynesia', hasFlag: false, region: Region.Oceania },
	PG: { name: 'Papua New Guinea', hasFlag: false, region: Region.Oceania },
	PH: { name: 'Philippines', hasFlag: true, region: Region.Asia },
	PK: { name: 'Pakistan', hasFlag: true, region: Region.Asia },
	PL: { name: 'Poland', hasFlag: true, region: Region.Europe },
	PM: { name: 'Saint Pierre and Miquelon', hasFlag: false, region: Region.NorthAmerica },
	PN: { name: 'Pitcairn', hasFlag: false, region: Region.Oceania },
	PR: { name: 'Puerto Rico', hasFlag: false, region: Region.NorthAmerica },
	PS: { name: 'Palestine, State of', hasFlag: false, region: Region.MiddleEast },
	PT: { name: 'Portugal', hasFlag: true, region: Region.Europe },
	PW: { name: 'Palau', hasFlag: false, region: Region.Oceania },
	PY: { name: 'Paraguay', hasFlag: true, region: Region.SouthAmerica },
	QA: { name: 'Qatar', hasFlag: false, region: Region.MiddleEast },
	RE: { name: 'Réunion', hasFlag: false, region: Region.Africa },
	RO: { name: 'Romania', hasFlag: true, region: Region.Europe },
	RS: { name: 'Serbia', hasFlag: true, region: Region.Europe },
	RU: { name: 'Russian Federation', hasFlag: true, region: Region.Europe },
	RW: { name: 'Rwanda', hasFlag: true, region: Region.Africa },
	SA: { name: 'Saudi Arabia', hasFlag: true, region: Region.MiddleEast },
	SB: { name: 'Solomon Islands', hasFlag: false, region: Region.Oceania },
	SC: { name: 'Seychelles', hasFlag: false, region: Region.Africa },
	SD: { name: 'Sudan', hasFlag: false, region: Region.Africa },
	SE: { name: 'Sweden', hasFlag: true, region: Region.Europe },
	SG: { name: 'Singapore', hasFlag: false, region: Region.Asia },
	SH: { name: 'Saint Helena, Ascension and Tristan da Cunha', hasFlag: false, region: Region.Africa },
	SI: { name: 'Slovenia', hasFlag: true, region: Region.Europe },
	SJ: { name: 'Svalbard and Jan Mayen', hasFlag: false, region: Region.Europe },
	SK: { name: 'Slovakia', hasFlag: true, region: Region.Europe },
	SL: { name: 'Sierra Leone', hasFlag: true, region: Region.Africa },
	SM: { name: 'San Marino', hasFlag: false, region: Region.Europe },
	SN: { name: 'Senegal', hasFlag: false, region: Region.Africa },
	SO: { name: 'Somalia', hasFlag: true, region: Region.Africa },
	SR: { name: 'Suriname', hasFlag: false, region: Region.SouthAmerica },
	SS: { name: 'South Sudan', hasFlag: false, region: Region.Africa },
	ST: { name: 'Sao Tome and Principe', hasFlag: false, region: Region.Africa },
	SV: { name: 'El Salvador', hasFlag: false, region: Region.CentralAmerica },
	SX: { name: 'Sint Maarten (Dutch part)', hasFlag: false, region: Region.NorthAmerica },
	SY: { name: 'Syrian Arab Republic', hasFlag: false, region: Region.MiddleEast },
	SZ: { name: 'Eswatini', hasFlag: false, region: Region.Africa },
	TC: { name: 'Turks and Caicos Islands', hasFlag: false, region: Region.NorthAmerica },
	TD: { name: 'Chad', hasFlag: false, region: Region.Africa },
	TF: { name: 'French Southern Territories', hasFlag: false, region: Region.Antarctica },
	TG: { name: 'Togo', hasFlag: false, region: Region.Africa },
	TH: { name: 'Thailand', hasFlag: true, region: Region.Asia },
	TJ: { name: 'Tajikistan', hasFlag: true, region: Region.Asia },
	TK: { name: 'Tokelau', hasFlag: false, region: Region.Oceania },
	TL: { name: 'Timor-Leste', hasFlag: false, region: Region.Asia },
	TM: { name: 'Turkmenistan', hasFlag: true, region: Region.Asia },
	TN: { name: 'Tunisia', hasFlag: false, region: Region.Africa },
	TO: { name: 'Tonga', hasFlag: false, region: Region.Oceania },
	TR: { name: 'Türkiye', hasFlag: true, region: Region.Europe },
	TT: { name: 'Trinidad and Tobago', hasFlag: false, region: Region.NorthAmerica },
	TV: { name: 'Tuvalu', hasFlag: false, region: Region.Oceania },
	TW: { name: 'Taiwan, Province of China', hasFlag: true, region: Region.Asia },
	TZ: { name: 'Tanzania, United Republic of', hasFlag: true, region: Region.Africa },
	UA: { name: 'Ukraine', hasFlag: true, region: Region.Europe },
	UG: { name: 'Uganda', hasFlag: true, region: Region.Africa },
	UM: { name: 'United States Minor Outlying Islands', hasFlag: false, region: Region.NorthAmerica },
	US: { name: 'United States of America', hasFlag: true, region: Region.NorthAmerica },
	UY: { name: 'Uruguay', hasFlag: false, region: Region.SouthAmerica },
	UZ: { name: 'Uzbekistan', hasFlag: true, region: Region.Asia },
	VA: { name: 'Holy See', hasFlag: false, region: Region.Europe },
	VC: { name: 'Saint Vincent and the Grenadines', hasFlag: false, region: Region.NorthAmerica },
	VE: { name: 'Venezuela, Bolivarian Republic of', hasFlag: false, region: Region.SouthAmerica },
	VG: { name: 'Virgin Islands (British)', hasFlag: false, region: Region.NorthAmerica },
	VI: { name: 'Virgin Islands (U.S.)', hasFlag: false, region: Region.NorthAmerica },
	VN: { name: 'Viet Nam', hasFlag: true, region: Region.Asia },
	VU: { name: 'Vanuatu', hasFlag: false, region: Region.Oceania },
	WF: { name: 'Wallis and Futuna', hasFlag: false, region: Region.Oceania },
	WS: { name: 'Samoa', hasFlag: true, region: Region.Oceania },
	YE: { name: 'Yemen', hasFlag: false, region: Region.MiddleEast },
	YT: { name: 'Mayotte', hasFlag: false, region: Region.Africa },
	ZA: { name: 'South Africa', hasFlag: true, region: Region.Africa },
	ZM: { name: 'Zambia', hasFlag: false, region: Region.Africa },
	ZW: { name: 'Zimbabwe', hasFlag: true, region: Region.Africa },
};
